# Algebra Sequences Series
![](https://tutoriale-video.ro/wp-content/uploads/2018/10/tipuri-de-secvente.jpg)
![](http://mrguesto.weebly.com/uploads/2/3/2/5/23253470/sequences_orig.png)
![](https://www.bossmaths.com/wp-content/uploads/Nonexs.013-1024x576.png)
![](https://sep.yimg.com/ay/mathmedia/sequences-and-series-28.jpg)    
參考:  
https://edublognss.wordpress.com/2013/04/16/famous-mathematical-sequences-and-series/

# 等差數列之和

## 1.數列之和函數為：summation

summation(一般項 a_i, (i, 初值, 終值)) 。

等差  
$\sum_{i=1}^{10} i$

等比  
$\sum_{i=1}^{10} i*2$  

指數  
$\sum_{i=1}^{10} i^2$  

In [17]:
import sympy as sp    
i=sp.Symbol('i')   
sp.summation(i, (i, 1, 10))    

In [15]:
import sympy as sp    
i=sp.Symbol('i')   
sp.summation(i*2, (i, 1, 10))    

In [19]:
sp.summation(i**2, (i, 1, 10))

## 2.嘗試從 1 到 11 的等差和。

In [59]:
1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10+11

66

In [1]:
import sympy as sp
import numpy as np
n,i= sp.symbols('n,i')
expre= n*5
expr_func= sp.lambdify(n,expre)
a=expr_func(np.arange(12))
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

### 2.1 定義等差d

In [3]:
d=a[2]-a[1]
d

5

### 2.2 通項 a[i], i [1,2,3...n]

註明:電腦從計 a[0] 計算,這里a[0]不使用

In [4]:

(a[1]+(n-1)*d).subs(n,11)

55

### 2.3 數列和

In [67]:
sp.summation(expre, (n, 1, 11)) 

396

### 2.4 計算公式  $\frac{n(n+1)}{2}$  由  n=10  也可要求。

In [13]:
import sympy as sp
n= sp.Symbol('n')

In [16]:
(n*(n + 1)/2)

n*(n + 1)/2

In [58]:
(n*(n + 1)/2).subs(n,11)

66

## 題型一

In [66]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(10) +1 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(12))
    print(a)
    St=f"己知 a{a2}={a[a2]},d={d},求a{a3}?"
    Val=a[a3]
    print(St)
    print(Val)

[4, 0, -8, -1, 8, -3, -5, 3, 2, 6]
[ 0  4  8 12 16 20 24 28 32 36 40 44]
己知 a10=40,d=4,求a3?
12
[ 0  1  2  3  4  5  6  7  8  9 10 11]
己知 a9=9,d=1,求a2?
2
[  0  -8 -16 -24 -32 -40 -48 -56 -64 -72 -80 -88]
己知 a1=-8,d=-8,求a6?
-48
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11]
己知 a3=-3,d=-1,求a8?
-8
[ 0  8 16 24 32 40 48 56 64 72 80 88]
己知 a3=24,d=8,求a8?
64
[  0  -3  -6  -9 -12 -15 -18 -21 -24 -27 -30 -33]
己知 a10=-30,d=-3,求a5?
-15
[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55]
己知 a2=-10,d=-5,求a8?
-40
[ 0  3  6  9 12 15 18 21 24 27 30 33]
己知 a1=3,d=3,求a7?
21
[ 0  2  4  6  8 10 12 14 16 18 20 22]
己知 a3=6,d=2,求a8?
16
[ 0  6 12 18 24 30 36 42 48 54 60 66]
己知 a8=48,d=6,求a1?
6


## 題型二

In [70]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(10) +1 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(21))
    print(a)
    St=f"己知 a{a2}={a[a2]},a{a3}={a[a3]},求?d"
    Val=d
    print(St)
    print(Val)

[3, -8, 1, -1, 9, -7, 8, 2, 5, -6]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]
己知 a10=30,a5=15,求?d
3
[   0   -8  -16  -24  -32  -40  -48  -56  -64  -72  -80  -88  -96 -104
 -112 -120 -128 -136 -144 -152 -160]
己知 a7=-56,a1=-8,求?d
-8
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
己知 a5=5,a9=9,求?d
1
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20]
己知 a6=-6,a1=-1,求?d
-1
[  0   9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144 153
 162 171 180]
己知 a3=27,a9=81,求?d
9
[   0   -7  -14  -21  -28  -35  -42  -49  -56  -63  -70  -77  -84  -91
  -98 -105 -112 -119 -126 -133 -140]
己知 a9=-63,a2=-14,求?d
-7
[  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136
 144 152 160]
己知 a10=80,a3=24,求?d
8
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
己知 a10=20,a5=10,求?d
2
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
己知 a6=30,a1=5,求?d
5
[   0   -6 

## 題型三

In [88]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(6) + 6 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(18))
    print(a)
    tem_=""
    for i,a_ in enumerate(a):
        if i>0 and i<4  :
            tem_ = tem_+str(a_ )+","
    St=r'己知 {}..{}, S{} ?'.format(tem_,a[a2],a2)
    Val=sp.summation(expre, (n, 1, a2))
    print(St)
    print(Val)

[-5, 7, 3, -7, 2, -2, 9, 4, 6, -8]
[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55 -60 -65 -70 -75 -80 -85]
己知 -5,-10,-15,..-35, S7 ?
-140
[  0   7  14  21  28  35  42  49  56  63  70  77  84  91  98 105 112 119]
己知 7,14,21,..56, S8 ?
252
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51]
己知 3,6,9,..21, S7 ?
84
[   0   -7  -14  -21  -28  -35  -42  -49  -56  -63  -70  -77  -84  -91
  -98 -105 -112 -119]
己知 -7,-14,-21,..-63, S9 ?
-315
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]
己知 2,4,6,..12, S6 ?
42
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30 -32 -34]
己知 -2,-4,-6,..-18, S9 ?
-90
[  0   9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144 153]
己知 9,18,27,..54, S6 ?
189
[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68]
己知 4,8,12,..24, S6 ?
84
[  0   6  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 102]
己知 6,12,18,..42, S7 ?
168
[   0   -8  -16  -24  -32  -40  -48  -56  -64  -72  -80  -88  -96 -104
 -112 -120 -128 -136]
己知 

## 題型四

In [91]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(6) + 6 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(18))
    print(a)
    St=r'己知 a1={},d={}, S{} ?'.format(a[1],d,a2)
    Val=sp.summation(expre, (n, 1, a2))
    print(St)
    print(Val)

[4, -8, 0, -9, 1, -5, 8, -4, 6, 5]
[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68]
己知 a1=4,d=4, S8 ?
144
[   0   -8  -16  -24  -32  -40  -48  -56  -64  -72  -80  -88  -96 -104
 -112 -120 -128 -136]
己知 a1=-8,d=-8, S7 ?
-224
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
己知 a1=1,d=1, S11 ?
66
[   0   -9  -18  -27  -36  -45  -54  -63  -72  -81  -90  -99 -108 -117
 -126 -135 -144 -153]
己知 a1=-9,d=-9, S8 ?
-324
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
己知 a1=1,d=1, S9 ?
45
[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55 -60 -65 -70 -75 -80 -85]
己知 a1=-5,d=-5, S10 ?
-275
[  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136]
己知 a1=8,d=8, S11 ?
528
[  0  -4  -8 -12 -16 -20 -24 -28 -32 -36 -40 -44 -48 -52 -56 -60 -64 -68]
己知 a1=-4,d=-4, S6 ?
-84
[  0   6  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 102]
己知 a1=6,d=6, S6 ?
126
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85]
己知 a1=5,d=5, S9 ?
225


## 3. 等比和

In [1]:
1-2+4-8+ 16 -32 +64- 128+ 256 -512 + 1024 

683

In [78]:
exper =-2**(-1)

-0.5

In [85]:
import sympy as sp
import numpy as np
n,i= sp.symbols('n,i')
expre= (-2) ** (n-1)
expr_func= sp.lambdify(n, expre)
n_arr=np.arange(12)
n_arr[0]=1
a=expr_func(n_arr)
a

array([   1,    1,   -2,    4,   -8,   16,  -32,   64, -128,  256, -512,
       1024], dtype=int32)

### 等比

In [87]:

q=a[4]/a[3]
q

-2.0

### 通項

In [88]:

expre.subs(n,11)

1024

In [89]:
a[1] * q**(11-1)

1024.0

### 和

In [97]:
(a[1]*(1-q**n)/(1-q)).subs(n,11) 

683.000000000000

In [95]:
(a[1]-a[11]*q)/(1-q)

683.0

In [94]:
sp.summation( expre, (n, 1, 11))     

683

![](https://appwk.baidu.com/naapi/doc/view?ih=673&o=jpg_6_0_______&iw=678&ix=0&iy=0&aimw=678&rn=1&doc_id=21ad731a59eef8c75fbfb3d0&pn=1&sign=095cfb97e48b57b1777292b350277067&type=1&app_ver=2.9.8.2&ua=bd_800_800_IncredibleS_2.9.8.2_2.3.7&bid=1&app_ua=IncredibleS&uid=&cuid=&fr=3&Bdi_bear=WIFI&from=3_10000&bduss=&pid=1&screen=800_800&sys_ver=2.3.7)

## 4  指數數列之和

$\sum_{i=1}^{10} 2^i$  

In [6]:
import sympy as sp
sp.init_printing("mathjax")                       #
from sympy import div,pdiv,rem,ZZ,QQ 
from IPython.display import Latex,HTML,Markdown    
from sympy.parsing.sympy_parser import parse_expr #文字字串, 解釋成, Sympy 運算式
i=sp.Symbol('i')
sp.summation(2 ** i  , (i, 1, 10))

### 4.1. N数列指數和

∑(i=1,N) i^2=N(N+1)(2N+1)/6

$\sum_{i=1}^{N} i^2  = \frac{N(N+1)(2N+1)}{6}$ 

In [20]:
N= sp.Symbol('N')
sp.summation(i**2, (i, 1, N))

In [21]:
sp.factor(_)


### 練習. 數列之和

第一項  a1 ，公差  d  等差列的第1項至第2項 n 要求一個術語的總和。  
對於初項為3、公比為2的等比數列，求出到第10項之和。  
∑(i=1,n) b1 r^(i−1) 問問你 另外，無限等比數列之和  n→∞  問問你 但是， 0<r<1 。  


（提示）

1. 計算如下。 在句子末尾添加時，不顯示結果。; 



In [22]:
a1 = sp.Symbol('a1')
sp.summation(a1 + ( i- 1)*d, (i, 1, n));

In [23]:
b1 = sp.Symbol('b1')
sum2 = sp.summation(b1*r**(i - 1), (i, 1, n))

In [24]:
sum2

   ⎛⎧    n       for r = 1⎞
   ⎜⎪                     ⎟
   ⎜⎪     n + 1           ⎟
b₁⋅⎜⎨r - r                ⎟
   ⎜⎪──────────  otherwise⎟
   ⎜⎪  1 - r              ⎟
   ⎝⎩                     ⎠
───────────────────────────
             r             

## 5.計算的階乘

4  計算的階乘。4! =4×3×2×1=24 是。 在 SymPy 中，階乘使用函數。factorial

In [40]:
factorial(4)

factorial2 函數計算每個場地。 5! ! =5×3×1=15  是。

In [41]:
factorial2(5)


練習
（練習）  3,2,1  最大數位由

使用數位 3、2 和 1 的單一動作可以建立的最大整數是什麼？

（提示）

(1+2)×3=9  那一點也不好。 如果你按原樣排列， 321  但是，使用冪可以創建更大的數位。

213  或者說， 312  或者說， 231  或者說， 321  或者...



## 6 數列之積product
$$\prod_{k=1}^{10} k= 10!$$


In [19]:
import sympy as sp
sp.factorial(10)

In [20]:
import sympy as sp
k=sp.symbols('k',integer=True)
sp.product(k, (k, 1, 10) )

### 6.1 例題


$$\prod_{k=2}^{2021} \frac{k^2-1}{K^2}$$

$$ A_1= \frac{2^2-1}{2^2} \cdot \frac{3^2-1}{3^2}  \cdot \frac{4^2-1}{4^2} \cdot \cdot \cdot \frac{2021^2-1}{2021^2}  $$


<details>
    <summary>Click to reveal solution</summary>
```    
$$ A_1= \frac{(2-1)(2+1)}{2^2} \cdot \frac{(3+1)(3-1)}{3^2}  \cdot \cdot \cdot \frac{(2021-1)(2021+1)}{2021^2}  $$    
$$ A_1= \frac{(1)(3)}{2^2} \cdot \frac{(2)(4)}{3^2}  \cdot \cdot \cdot \frac{(2020)(2022)}{2021^2}  $$
$$ A_1= \frac{(1 * 2 * 3 * 4 \cdot \cdot \cdot 2020) \cdot ( 3 * 4 \cdot \cdot \cdot 2020 * 2021*2022)}{(2 * 3 * 4 \cdot \cdot \cdot 2020 * 2021) *(2 * 3 * 4 \cdot \cdot \cdot 2020 * 2021)}  $$
$$ A_1= \frac{ 2022}{2021 *2} = \frac{1011}{2021} $$    
$$ A_1= \frac{ 2022}{2021 *2} = \frac{1011}{2021} $$
```
</details>




In [21]:
# 計算
print(1011/2021)

# 程式一
A1=1 
for i in range(2,2022): 
    A1 *= (i**2-1)/ (i**2)
print(A1)

# 程式二
A2=1 
for i in range(2,2022): 
    A2 *= sp.S(i**2-1) / sp.S(i**2)
print(A2)


0.500247402276101
0.5002474022761008
1011/2021


In [16]:
expre=(k**2-1)/(k**2)
sp.product(expre, (k, 2, 2021) )

## Pascal's Triangel

In [4]:
from sympy import Symbol, Rational, binomial, expand_func
n = Symbol('n', integer=True, positive=True)

In [5]:
binomial(15, 8)

6435

In [10]:
binomial(n, -1)

0

In [11]:
for N in range(8):
    print([binomial(N, i) for i in range(N + 1)])

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]
[1, 6, 15, 20, 15, 6, 1]
[1, 7, 21, 35, 35, 21, 7, 1]


## fibonacci

In [12]:
from sympy import fibonacci, Symbol
[fibonacci(x) for x in range(11)]

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

In [13]:
fibonacci(5, Symbol('t'))

t**4 + 3*t**2 + 1

## 7. 資料收集,未整理

### Sequence
https://en.wikipedia.org/wiki/Sequence


### List of integer sequences 

https://en.wikipedia.org/wiki/List_of_integer_sequences


###  List of mathematical series
https://en.wikipedia.org/wiki/List_of_mathematical_series

Famous Mathematical Sequences and Series | Edu-Blog

https://edublognss.wordpress.com/2013/04/16/famous-mathematical-sequences-and-series/#:~:text=Only%20a%20few%20of%20the%20more%20famous%20mathematical,of%20numbers%20so%20sacrosanct%20or%20important%20or%20famous.

### 7.1.泰勒函數擴展
sinx  在  x=0  周圍  x5  泰勒展開到部分的示例。

（Python 從零開始， x5  是 x0  第六，我想我應該記住...




In [77]:
x = Symbol('x', real=True)
series(sin(x), x, 0, 6)

$e^{ix} $   （ i  泰勒部署的虛數單位）

In [78]:
series(exp(I*x), x, 0, 6)

如果將假想部分與im函數一起使用...（順便說一句，實部是re。）

In [79]:
im(_)

cos x,tan x  讓我們嘗試泰勒展開式。



### sequences  
https://docs.sympy.org/latest/modules/series/sequences.html

https://www.youtube.com/watch?v=_cooC3yG_p0   
https://www.youtube.com/watch?v=VgVJrSJxkDk   
https://www.youtube.com/watch?v=Zd9xsSeBZlA    
https://www.youtube.com/watch?v=ihxJN6ZC9HE   

### Combinatorial
https://docs.sympy.org/latest/modules/functions/combinatorial.html   


### series
https://www.youtube.com/watch?v=neUB-5KO_Wc  
https://www.youtube.com/watch?v=Jwtn5_d2YCs   
https://www.youtube.com/watch?v=L-JqHo4-W4k   
https://www.youtube.com/watch?v=neUB-5KO_Wc  
riemann series theorem 
复變函數   
共形 及 riemann 几何   
tayler seires  
erul 
riemann 
fourier 



# Sequences
A sequence is a finite or infinite lazily evaluated list
sympy.series.sequences.sequence(seq, limits=None)[source]
Returns appropriate sequence object.

Explanation

If seq is a sympy sequence, returns SeqPer object otherwise returns SeqFormula object.

Examples

In [2]:
from sympy import sequence
from sympy.abc import n
sequence(n**2, (n, 0, 5))
#SeqFormula(n**2, (n, 0, 5))


SeqFormula(n**2, (n, 0, 5))

In [3]:
sequence((1, 2, 3), (n, 0, 5))
#SeqPer((1, 2, 3), (n, 0, 5))

SeqPer((1, 2, 3), (n, 0, 5))

See also sympy.series.sequences.SeqPer, sympy.series.sequences.SeqFormula
Sequences Base
class sympy.series.sequences.SeqBase(*args)[source]
Base class for sequences

coeff(pt)[source]
Returns the coefficient at point pt

coeff_mul(other)[source]
Should be used when other is not a sequence. Should be defined to define custom behaviour.

Examples


In [4]:
from sympy import SeqFormula
from sympy.abc import n
SeqFormula(n**2).coeff_mul(2)


SeqFormula(2*n**2, (n, 0, oo))

In [6]:
from sympy import sequence, sqrt, oo, lucas
SeqFormula(2*n**2, (n, 0, oo))

SeqFormula(2*n**2, (n, 0, oo))

Notes

‘*’ defines multiplication of sequences with sequences only.

find_linear_recurrence(n, d=None, gfvar=None)[source]
Finds the shortest linear recurrence that satisfies the first n terms of sequence of order ≤ n/2 if possible. If d is specified, find shortest linear recurrence of order ≤ min(d, n/2) if possible. Returns list of coefficients [b(1), b(2), ...] corresponding to the recurrence relation x(n) = b(1)*x(n-1) + b(2)*x(n-2) + ... Returns [] if no recurrence is found. If gfvar is specified, also returns ordinary generating function as a function of gfvar.

Examples


In [7]:
from sympy import sequence, sqrt, oo, lucas
from sympy.abc import n, x, y
sequence(n**2).find_linear_recurrence(10, 2)


[]

In [8]:
sequence(n**2).find_linear_recurrence(10)

[3, -3, 1]

In [9]:
sequence(2**n).find_linear_recurrence(10)

[2]

In [10]:
sequence(23*n**4+91*n**2).find_linear_recurrence(10)

[5, -10, 10, -5, 1]

In [11]:
sequence(sqrt(5)*(((1 + sqrt(5))/2)**n - (-(1 + sqrt(5))/2)**(-n))/5).find_linear_recurrence(10)

[1, 1]

In [12]:
sequence(x+y*(-2)**(-n), (n, 0, oo)).find_linear_recurrence(30)

[1/2, 1/2]

In [14]:
sequence(3*5**n + 12).find_linear_recurrence(20,gfvar=x)

([6, -5], 3*(5 - 21*x)/((x - 1)*(5*x - 1)))

property free_symbols
This method returns the symbols in the object, excluding those that take on a specific value (i.e. the dummy symbols).


In [15]:
from sympy import SeqFormula
from sympy.abc import n, m
SeqFormula(m*n**2, (n, 0, 5)).free_symbols

{m}

property gen
Returns the generator for the sequence

property interval
The interval on which the sequence is defined

property length
Length of the sequence

property start
The starting point of the sequence. This point is included

property stop
The ending point of the sequence. This point is included

property variables
Returns a tuple of variables that are bounded



## Elementary Sequences
class sympy.series.sequences.SeqFormula(formula, limits=None)[source]
Represents sequence based on a formula.

Elements are generated using a formula.

In [16]:
from sympy import SeqFormula, oo, Symbol
n = Symbol('n')
s = SeqFormula(n**2, (n, 0, 5))
s.formula
n**2

n**2

For value at a particular point

In [17]:
s.coeff(3)

9

supports slicing

In [18]:
s[:]

[0, 1, 4, 9, 16, 25]

iterable

In [19]:
list(s)

[0, 1, 4, 9, 16, 25]

sequence starts from negative infinity

In [20]:
SeqFormula(n**2, (-oo, 0))[0:6]

[0, 1, 4, 9, 16, 25]

See also sympy.series.sequences.SeqPer
coeff_mul(coeff)[source]
See docstring of SeqBase.coeff_mul

class sympy.series.sequences.SeqPer(periodical, limits=None)[source]
Represents a periodic sequence.

The elements are repeated after a given period.


In [22]:
from sympy import SeqPer, oo
from sympy.abc import k

In [23]:
s = SeqPer((1, 2, 3), (0, 5))
s.periodical

(1, 2, 3)

In [24]:
s.period

3

For value at a particular point

In [25]:
s.coeff(3)

1

In [27]:
#supports slicing
s[:]
#[1, 2, 3, 1, 2, 3]
#iterable
list(s)
#[1, 2, 3, 1, 2, 3]
#sequence starts from negative infinity
SeqPer((1, 2, 3), (-oo, 0))[0:6]
#[1, 2, 3, 1, 2, 3]
#Periodic formulas
SeqPer((k, k**2, k**3), (k, 0, oo))[0:6]
#[0, 1, 8, 3, 16, 125]
#See also sympy.series.sequences.SeqFormula
#coeff_mul(coeff)[source]
#See docstring of SeqBase.coeff_mul


[0, 1, 8, 3, 16, 125]

## Singleton Sequences


class sympy.series.sequences.EmptySequence(*args, **kwargs)[source]
Represents an empty sequence.

The empty sequence is also available as a singleton as S.EmptySequence.

In [29]:
from sympy import EmptySequence, SeqPer
from sympy.abc import x
EmptySequence
#EmptySequence
SeqPer((1, 2), (x, 0, 10)) + EmptySequence
#SeqPer((1, 2), (x, 0, 10))
SeqPer((1, 2)) * EmptySequence
#EmptySequence
EmptySequence.coeff_mul(-1)
#EmptySequence
#coeff_mul(coeff)[source]
#See docstring of SeqBase.coeff_mul

EmptySequence

## Compound Sequences
class sympy.series.sequences.SeqAdd(*args, **kwargs)[source]
Represents term-wise addition of sequences.

Rules:
The interval on which sequence is defined is the intersection of respective intervals of sequences.

Anything + EmptySequence remains unchanged.

Other rules are defined in _add methods of sequence classes.


In [32]:
from sympy import EmptySequence, oo, SeqAdd, SeqPer, SeqFormula
from sympy.abc import n
SeqAdd(SeqPer((1, 2), (n, 0, oo)), EmptySequence)
# SeqPer((1, 2), (n, 0, oo))
SeqAdd(SeqPer((1, 2), (n, 0, 5)), SeqPer((1, 2), (n, 6, 10)))
# EmptySequence
SeqAdd(SeqPer((1, 2), (n, 0, oo)), SeqFormula(n**2, (n, 0, oo)))
# SeqAdd(SeqFormula(n**2, (n, 0, oo)), SeqPer((1, 2), (n, 0, oo)))
SeqAdd(SeqFormula(n**3), SeqFormula(n**2))
# SeqFormula(n**3 + n**2, (n, 0, oo))

SeqFormula(n**3 + n**2, (n, 0, oo))

See also sympy.series.sequences.SeqMul
static reduce(args)[source]
Simplify SeqAdd using known rules.

Iterates through all pairs and ask the constituent sequences if they can simplify themselves with any other constituent.

Notes

adapted from Union.reduce

class sympy.series.sequences.SeqMul(*args, **kwargs)[source]
Represents term-wise multiplication of sequences.

Explanation

Handles multiplication of sequences only. For multiplication with other objects see SeqBase.coeff_mul().

Rules:
The interval on which sequence is defined is the intersection of respective intervals of sequences.

Anything * EmptySequence returns EmptySequence.

Other rules are defined in _mul methods of sequence classes.


In [33]:
from sympy import EmptySequence, oo, SeqMul, SeqPer, SeqFormula
from sympy.abc import n
SeqMul(SeqPer((1, 2), (n, 0, oo)), EmptySequence)
#EmptySequence
SeqMul(SeqPer((1, 2), (n, 0, 5)), SeqPer((1, 2), (n, 6, 10)))
#EmptySequence
SeqMul(SeqPer((1, 2), (n, 0, oo)), SeqFormula(n**2))
#SeqMul(SeqFormula(n**2, (n, 0, oo)), SeqPer((1, 2), (n, 0, oo)))
SeqMul(SeqFormula(n**3), SeqFormula(n**2))
#SeqFormula(n**5, (n, 0, oo))

SeqFormula(n**5, (n, 0, oo))

See also sympy.series.sequences.SeqAdd
static reduce(args)[source]
Simplify a SeqMul using known rules.

Explanation

Iterates through all pairs and ask the constituent sequences if they can simplify themselves with any other constituent.

Notes

adapted from Union.reduce

# Combinatorial

## bell

In [2]:
from sympy import bell, Symbol, symbols
[bell(n) for n in range(11)]
#[1, 1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975]


[1, 1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975]

In [3]:
bell(30)
#846749014511809332450147


846749014511809332450147

In [4]:
bell(4, Symbol('t'))
#t**4 + 6*t**3 + 7*t**2 + t


t**4 + 6*t**3 + 7*t**2 + t

In [5]:
bell(6, 2, symbols('x:6')[1:])
#6*x1*x5 + 15*x2*x4 + 10*x3**2

6*x1*x5 + 15*x2*x4 + 10*x3**2

## bernoulli¶

In [7]:
from sympy import bernoulli
[bernoulli(n) for n in range(11)]
#[1, -1/2, 1/6, 0, -1/30, 0, 1/42, 0, -1/30, 0, 5/66]


[1, -1/2, 1/6, 0, -1/30, 0, 1/42, 0, -1/30, 0, 5/66]

In [8]:
bernoulli(1000001)
#0

0

## binomial¶

In [9]:
from sympy import Symbol, Rational, binomial, expand_func
n = Symbol('n', integer=True, positive=True)
binomial(15, 8)
#6435


6435

In [ ]:
binomial(n, -1)
#0



In [ ]:
for N in range(8):
    print([binomial(N, i) for i in range(N + 1)])



In [ ]:
# As can a given diagonal, e.g. the 4th diagonal:
N = -4
[binomial(N, i) for i in range(1 - N)]
#[1, -4, 10, -20, 35]


In [ ]:
binomial(Rational(5, 4), 3)
#-5/128


In [ ]:
binomial(Rational(-5, 4), 3)
#-195/128


In [10]:
binomial(n, 3)


binomial(n, 3)

In [12]:
binomial(n, 3).expand(func=True)


n**3/6 - n**2/2 + n/3

In [14]:
expand_func(binomial(n, 3))
#n*(n - 2)*(n - 1)/6


n*(n - 2)*(n - 1)/6

## catalan

In [17]:
from sympy import (Symbol, binomial, gamma, hyper, catalan,
                   diff, combsimp, Rational, I)
[catalan(i) for i in range(1,10)]
#[1, 2, 5, 14, 42, 132, 429, 1430, 4862]

[1, 2, 5, 14, 42, 132, 429, 1430, 4862]

In [18]:
n = Symbol("n", integer=True)
catalan(n)

catalan(n)

In [21]:
catalan(n).rewrite(binomial)
#binomial(2*n, n)/(n + 1)

binomial(2*n, n)/(n + 1)

In [20]:
catalan(n).rewrite(gamma)
#4**n*gamma(n + 1/2)/(sqrt(pi)*gamma(n + 2))

4**n*gamma(n + 1/2)/(sqrt(pi)*gamma(n + 2))

In [22]:
catalan(n).rewrite(hyper)
#hyper((1 - n, -n), (2,), 1)


hyper((1 - n, -n), (2,), 1)

In [23]:
catalan(Rational(1, 2)).rewrite(gamma)
#8/(3*pi)

8/(3*pi)

In [24]:
diff(catalan(n), n)
#(polygamma(0, n + 1/2) - polygamma(0, n + 2) + log(4))*catalan(n)

(polygamma(0, n + 1/2) - polygamma(0, n + 2) + log(4))*catalan(n)

In [25]:
combsimp((catalan(n + 1)/catalan(n)).rewrite(binomial))
#2*(2*n + 1)/(n + 2)

2*(2*n + 1)/(n + 2)

In [26]:
catalan(I).rewrite(gamma)
#4**I*gamma(1/2 + I)/(sqrt(pi)*gamma(2 + I))

4**I*gamma(1/2 + I)/(sqrt(pi)*gamma(2 + I))

In [27]:
catalan(I).evalf(20)
#0.39764993382373624267 - 0.020884341620842555705*I

0.39764993382373624267 - 0.020884341620842555704*I

## euler

$E_{2n} = I \sum_{k=1}^{2n+1} \sum_{j=0}^k \binom{k}{j}
\frac{(-1)^j (k-2j)^{2n+1}}{2^k I^k k}$

$E_n = 2^n E_n\left(\frac{1}{2}\right).$

$E_n(x) = \sum_{k=0}^n \binom{n}{k} \frac{E_k}{2^k}
\left(x - \frac{1}{2}\right)^{n-k}.$

euler(n) gives the nth Euler number, En.

euler(n, x) gives the nth Euler polynomial, En(x).

In [5]:
from sympy import Symbol, S
from sympy.functions import euler
_=[euler(n) for n in range(10)]
display(_)
#[1, 0, -1, 0, 5, 0, -61, 0, 1385, 0]
n = Symbol("n")
_=euler(n + 2*n)
display(_)
# euler(3*n)
x = Symbol("x")
_=euler(n, x)
display(_)
#euler(n, x)
_=euler(0, x)
display(_)
#1
_=euler(1, x)
display(_)
#x - 1/2
_=euler(2, x)
display(_)
#x**2 - x
_=euler(3, x)
display(_)
#x**3 - 3*x**2/2 + 1/4
_=euler(4, x)
display(_)
#x**4 - 2*x**3 + x
_=euler(12, S.Half)
display(_)
#2702765/4096
_=euler(12)
display(_)
#2702765

[1, 0, -1, 0, 5, 0, -61, 0, 1385, 0]

euler(3*n)

euler(n, x)

1

x - 1/2

x**2 - x

x**3 - 3*x**2/2 + 1/4

x**4 - 2*x**3 + x

2702765/4096

2702765

## factorial

Examples

Run code block in SymPy Live
from sympy import Symbol, factorial, S
n = Symbol('n', integer=True)
Run code block in SymPy Live
factorial(0)
1
Run code block in SymPy Live
factorial(7)
5040
Run code block in SymPy Live
factorial(-2)
zoo
Run code block in SymPy Live
factorial(n)
factorial(n)
Run code block in SymPy Live
factorial(2*n)
factorial(2*n)
Run code block in SymPy Live
factorial(S(1)/2)
factorial(1/2)

## subfactorial
$\begin{split}!n = \begin{cases} 1 & n = 0 \\ 0 & n = 1 \\
(n-1)(!(n-1) + !(n-2)) & n > 1 \end{cases}\end{split}$

It can also be written as int(round(n!/exp(1))) but the recursive definition with caching is implemented for this function.

An interesting analytic expression is the following

$!x = \Gamma(x + 1, -1)/e$

which is valid for non-negative integers x. The above formula is not very useful incase of non-integers. Γ(x+1,−1) is single-valued only for integral arguments x, elsewhere on the positive real axis it has an infinite number of branches none of which are real.



In [6]:
from sympy import subfactorial
from sympy.abc import n
subfactorial(n + 1)
subfactorial(n + 1)
subfactorial(5)
#44

44

## factorial2 / double 
The double factorial n!!, not to be confused with (n!)!

The double factorial is defined for nonnegative integers and for odd negative integers as:


$
\begin{split}n!! = \begin{cases} 1 & n = 0 \\
n(n-2)(n-4) \cdots 1 & n\ \text{positive odd} \\
n(n-2)(n-4) \cdots 2 & n\ \text{positive even} \\
(n+2)!!/(n+2) & n\ \text{negative odd} \end{cases}\end{split}
$

In [7]:
from sympy import factorial2, var
n = var('n')
n
n
factorial2(n + 1)
factorial2(n + 1)
factorial2(5)
15
factorial2(-1)
1
factorial2(-5)
1/3

0.3333333333333333

## FallingFactorial
Falling factorial (related to rising factorial) is a double valued function arising in concrete mathematics, hypergeometric functions and series expansions. It is defined by  

$ff(x,k) = x \cdot (x-1) \cdots (x-k+1)$  
  
ff(x,k)=x⋅(x−1)⋯(x−k+1)   
where x can be arbitrary expression and k is an integer. For more information check “Concrete mathematics” by Graham, pp. 66 or visit http://mathworld.wolfram.com/FallingFactorial.html page.

When x is a Poly instance of degree >= 1 with single variable,  

$ ff(x,k) = x(y) \cdot x(y-1) \cdots x(y-k+1)$


ff(x,k)=x(y)⋅x(y−1)⋯x(y−k+1), where y is the variable of x. This is as described in Peter Paule, “Greatest Factorial Factorization and Symbolic Summation”, Journal of Symbolic Computation, vol. 20, pp. 235-268, 1995.

In [13]:
from sympy import ff, Poly, Symbol
from sympy.abc import x
n = Symbol('n', integer=True)

ff(x, 0)
1
ff(5, 5)
120
ff(x, 5) == x*(x - 1)*(x - 2)*(x - 3)*(x - 4)
True
ff(Poly(x**2, x), 2)
Poly(x**4 - 2*x**3 + x**2, x, domain='ZZ')
ff(n, n)
#factorial(n)

#Rewriting is complicated unless the relationship between the arguments is known, but falling factorial can be rewritten in terms of gamma, factorial and binomial and rising factorial.

from sympy import factorial, rf, gamma, binomial, Symbol
n = Symbol('n', integer=True, positive=True)
F = ff(n, n - 2)
for i in (rf, ff, factorial, binomial, gamma):
    F.rewrite(i)

#RisingFactorial(3, n - 2)
#FallingFactorial(n, n - 2)
#factorial(n)/2
binomial(n, n - 2)*factorial(n - 2)
#gamma(n + 1)/2

binomial(n, n - 2)*factorial(n - 2)